# Generated by Django 6.0.5 on 2026-06-09 03:48

import django.db.models.deletion
import django.utils.timezone
import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=67)),
                ('image', models.ImageField(upload_to=web.models.character.img_upload_to)),
                ('desc', models.TextField(max_length=6767)),
                ('bg_image', models.ImageField(upload_to=web.models.character.bg_upload_to)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
