# Generated by Django 6.0.5 on 2026-06-23 04:40

import django.db.models.deletion
import django.utils.timezone
import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bg_image',
            field=models.ImageField(default='character/bg/default_bg.png', upload_to=web.models.character.bg_upload_to),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.character')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
