# Generated by Django 6.0.5 on 2026-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
