# Generated by Django 6.0.5 on 2026-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_message_total_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='inputs',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='output',
            field=models.TextField(max_length=1000),
        ),
    ]
