# Generated by Django 6.0.5 on 2026-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_message_inputs_alter_message_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='output',
            field=models.TextField(),
        ),
    ]
