# Generated by Django 6.0.5 on 2026-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_systemprompt_alter_message_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
